# Generated by Django 6.1 on 2026-10-08 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=100, unique=True)),
                ('valor', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos_sitio_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contenido del sitio',
                'verbose_name_plural': 'contenidos del sitio',
                'ordering': ('clave',),
            },
        ),
        migrations.CreateModel(
            name='RegistroAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('eliminacion', 'Eliminación')], max_length=15)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('resumen', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_administrativas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro administrativo',
                'verbose_name_plural': 'registros administrativos',
                'ordering': ('-creado_en',),
            },
        ),
    ]
